"""Shared utilities for Lucius platform."""

from shared.credentials import (
    Credential,
    CredentialError,
    CredentialManager,
    get_credential_manager,
)
from shared.interfaces import (
    DataCleanerInterface,
    DependencyParserInterface,
    EventEmitterInterface,
    EventHandlerInterface,
    GrantRepositoryInterface,
    GrantServiceInterface,
    NotificationDispatcherInterface,
    NotificationInterface,
    ProcessorInterface,
    RepositoryInterface,
    ScannerInterface,
    ScanServiceInterface,
    ThreatAnalyzerInterface,
    ThreatScoringModelInterface,
    VulnerabilityDatabaseInterface,
    VulnerabilityRepositoryInterface,
)

__all__ = [
    "Credential",
    "CredentialError",
    "CredentialManager",
    "get_credential_manager",
    "DataCleanerInterface",
    "DependencyParserInterface",
    "EventEmitterInterface",
    "EventHandlerInterface",
    "GrantRepositoryInterface",
    "GrantServiceInterface",
    "NotificationDispatcherInterface",
    "NotificationInterface",
    "ProcessorInterface",
    "RepositoryInterface",
    "ScannerInterface",
    "ScanServiceInterface",
    "ThreatAnalyzerInterface",
    "ThreatScoringModelInterface",
    "VulnerabilityDatabaseInterface",
    "VulnerabilityRepositoryInterface",
]
from shared.logging import get_logger, setup_logging
from shared.types import (
    APIResponse,
    Dependency,
    Grant,
    GrantStatus,
    Milestone,
    NonprofitOrganization,
    Notification,
    NotificationChannel,
    NotificationStatus,
    PaginatedResponse,
    Priority,
    ScanResult,
    ScanStatus,
    Severity,
    Vulnerability,
)

__all__ = [
    # Logging
    "get_logger",
    "setup_logging",
    # Enums
    "Severity",
    "ScanStatus",
    "GrantStatus",
    "Priority",
    "NotificationChannel",
    "NotificationStatus",
    # Types
    "Dependency",
    "Vulnerability",
    "ScanResult",
    "Grant",
    "Milestone",
    "Notification",
    "NonprofitOrganization",
    "APIResponse",
    "PaginatedResponse",
    # Interfaces
    "ScannerInterface",
    "DependencyParserInterface",
    "VulnerabilityDatabaseInterface",
    "NotificationInterface",
    "NotificationDispatcherInterface",
    "ProcessorInterface",
    "DataCleanerInterface",
    "RepositoryInterface",
    "VulnerabilityRepositoryInterface",
    "GrantRepositoryInterface",
    "ThreatAnalyzerInterface",
    "ThreatScoringModelInterface",
    "GrantServiceInterface",
    "ScanServiceInterface",
    "EventHandlerInterface",
    "EventEmitterInterface",
]
